import Head from 'next/head'
import questions from "../questions.json";
import styles from '../styles/Home.module.css'
import { useState } from "react";
import Link from 'next/link'
import Image from 'next/image'
// import Pizza from  

export default function Answers() {

    return (
        <div className={styles.container}>
            <Head>
                <title>Where to eat?</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div>
                    <div>Based on your answers...</div>
                </div>
                <div>
                    <div>This is your top choice</div>
                </div>

                <div className={styles.questions}>
                    <div>

                    </div>
                    <div>
                        <Image src={"/ivan-torres-unsplash.jpg"} width={200} height={150} />
                    </div>
                </div>

                <Link href="question4"><button>Previous</button></Link>
            </main>
        </div>
    )
}