import Head from 'next/head'
import questions from "../questions.json";
import styles from '../styles/Home.module.css'
import { useState } from "react";
import Link from 'next/link'
import Image from 'next/image'
// import Pizza from  

export default function Question2() {

    return (
        <div className={styles.container}>
            <Head>
                <title>Where to eat?</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div>
                    <div>Question 2 of 4</div>
                </div>

                <div className={styles.questionsImg}>
                <p style={{
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                    }}>
                    The one that makes you really hungry right now
                </p>
                        <div>
                            <Link href="question3"><button><Image src={"/mike-unsplash.jpg"} width={350} height={250} />Burger & Fries</button></Link>
                            <Link href="question3"><button><Image src={"/stefan-schauberger-unsplash.jpg"} width={350} height={250} />Pasta</button></Link>
                        </div>
                </div>

                <Link href="question1"><button>Previous</button></Link>
            </main>
        </div>
    )
}