import Head from 'next/head'
import questions from "../questions.json";
import styles from '../styles/Home.module.css'
import { useState } from "react";
import Link from 'next/link'
import Image from 'next/image'
// import Pizza from  

export default function Question1() {

    return (
        <div className={styles.container}>
            <Head>
                <title>Where to eat?</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div>
                    <div>Question 1 of 4</div>
                </div>

                <div className={styles.questionsImg}>
                <p style={{
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                    }}>
                    The one that makes you really hungry right now
                </p>
                        <div>
                            <Link href="question2"><button><Image src={"/ivan-torres-unsplash.jpg"} width={350} height={250} />Pizza</button></Link>
                            <Link href="question2"><button><Image src={"/loes-klinker-unsplash.jpg"} width={350} height={250} />Greek Salad</button></Link>
                        </div>
                </div>

                <Link href="/"><button>Previous</button></Link>
            </main>
        </div>
    )
}