import Head from 'next/head'
import questions from "../questions.json";
import styles from '../styles/Home.module.css'
import { useState } from "react";
import Link from 'next/link'
import Image from 'next/image'
// import Pizza from  

export default function Question3() {

    return (
        <div className={styles.container}>
            <Head>
                <title>Where to eat?</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div>
                    <div>Question 3 of 4</div>
                </div>

                <div className={styles.questions}>
                    How would you like to enjoy your food?
                        <div>
                            <Link href="question4"><button>Dine in</button></Link>
                            <Link href="question4"><button>Take out</button></Link>
                            <Link href="question4"><button>Pick up</button></Link>
                            <Link href="question4"><button>Delivered</button></Link>
                        </div>
                </div>

                <Link href="question2"><button>Previous</button></Link>
            </main>
        </div>
    )
}