import Head from 'next/head'
import questions from "../questions.json";
import styles from '../styles/Home.module.css'
import { useState } from "react";
import Link from 'next/link'
import Image from 'next/image'
// import Pizza from  

export default function Question3() {

    return (
        <div className={styles.container}>
            <Head>
                <title>Where to eat?</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div>
                    <div>Question 4 of 4</div>
                </div>

                <div className={styles.questions}>
                    The one that makes you really hungry right now
                        <div>
                            <Link href="answers"><button>$</button></Link>
                            <Link href="answers"><button>$$</button></Link>
                            <Link href="answers"><button>$$$</button></Link>
                            <Link href="answers"><button>I don't care</button></Link>
                        </div>
                </div>

                <Link href="question3"><button>Previous</button></Link>
            </main>
        </div>
    )
}