import Head from 'next/head'
import questions from "../questions.json";
import styles from '../styles/Home.module.css'
import { useState } from "react";
import Link from 'next/link'
import Image from 'next/image'
// import Pizza from  

export default function Questions() {
    const [currentQuestion, setCurrentQuestion] = useState(0);

    const handlePrevious = () => {
        const prevQues = currentQuestion - 1;
        prevQues >= 0 && setCurrentQuestion(prevQues);
    };
  
    const handleNext = () => {
        const nextQues = currentQuestion + 1;
        nextQues < questions.length && setCurrentQuestion(nextQues);
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Where to eat?</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div>
                    <div>{questions[currentQuestion].question}</div>
                </div>

                <div className={styles.questions}>
                    {questions[currentQuestion].answerOptions.map((answer, index) => (
                        <div key={index}>
                            <button onClick={handleNext}>{answer.answer}</button>
                        </div>
                    ))}
                </div>

                <button onClick={handlePrevious}>Previous</button>
                {/* <div>
                    <div>Question 1 of 4</div>
                </div>

                <div className={styles.questions}>
                    The one that makes you really hungry right now
                        <div> */}
                            {/* <button onClick={handleNext}><img src="/public/ivan-torres-unsplash.jpg" alt="pizza" /></button> */}
                            {/* <button><img src="public/ivan-torres-unsplash.jpg" alt="pizza" /></button> */}
                            {/* <Link><button><Image src={"/ivan-torres-unsplash.jpg"} width={200} height={150} />Pizza</button></Link>
                            <button><Image src={"/loes-klinker-unsplash.jpg"} width={200} height={150} />Greek Salad</button> */}
                        {/* </div>
                </div> */}

                {/* <button onClick={handlePrevious}>Previous</button> */}
                {/* <Link href="index.js">
                    <button>Previous</button>
                </Link> */}
            </main>
        </div>
    )
}